management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
server:
  port: 9999
spring:
  application:
    name: zuul-api
ribbon:
  eager-load:
    enabled: true
  
# comment below routes you can use microservice instance names via zuul
zuul:
  sensitive-headers:
  routes:
    first-app: first/**
    sc-config: second/**
    oauth-service: oauth-service/**
  ignore-security-headers: false
  
